export const ConstantCode = {
    I: 0,
    PI: 1,
    E: 2,
    EULERS_CONSTANT: 3,
    GRAVITY_EARTH: 4,
    SOLAR_CON: 5,
    GRAVITY_CONSTANT: 6,
    AVOGADROS_NUMBER: 7,
    GAS_CONSTANT: 8,
    BOLTZMANN_CONSTANT: 9,
    STEFAN_BOLTZMANN_CONSTANT: 10,
    CULOMBS_CONSTANT: 11,
    EPSILON_ZERO: 12,
    MU_ZERO: 13,
    SPEED_OF_LIGHT: 14,
    PLANCK_CONSTANT: 15,
    ELEMENTARY_CHARGE: 16,
    MASS_ELECTRON: 17,
    MASS_PROTON: 18,
    MASS_NEUTRON: 19,
    ATOMIC_MASS_CONSTANT: 20,
    FERMI_RADIUS: 21,
    TRUE: 22,
    FALSE: 23,
    PHI: 24,
    INFINITY: 25
}

export const ConstantByLatex = {
    "i": ConstantCode.I,
    "\\pi": ConstantCode.PI,
    "e": ConstantCode.EULERS_CONSTANT,
    "\\gamma": ConstantCode.EULERS_CONSTANT,
    "g": ConstantCode.GRAVITY_EARTH,
    "c": ConstantCode.SOLAR_CON,
    "G": ConstantCode.GRAVITY_CONSTANT,
    "N_A": ConstantCode.AVOGADROS_NUMBER,
    "R": ConstantCode.GAS_CONSTANT,
    "k_B": ConstantCode.BOLTZMANN_CONSTANT,
    "h": ConstantCode.PLANCK_CONSTANT,
    "k_e": ConstantCode.CULOMBS_CONSTANT,
    "\\varepsilon_0": ConstantCode.EPSILON_ZERO,
    "\\mu_0": ConstantCode.MU_ZERO,
    "c_0": ConstantCode.SPEED_OF_LIGHT,
    "l_P": ConstantCode.PLANCK_CONSTANT,
    "q_e": ConstantCode.ELEMENTARY_CHARGE,
    "m_e": ConstantCode.MASS_ELECTRON,
    "m_p": ConstantCode.MASS_PROTON,
    "m_n": ConstantCode.MASS_NEUTRON,
    "m_u": ConstantCode.ATOMIC_MASS_CONSTANT,
    "R_0": ConstantCode.FERMI_RADIUS,
    "\\mathrm{true}": ConstantCode.TRUE,
    "\\mathrm{false}": ConstantCode.FALSE,
    "\\varphi": ConstantCode.PHI,
    "\\infty": ConstantCode.INFINITY
}